import {parseLightMode,type LightMode} from './scene/lighting';
import {photoViews} from './data/photoViews';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Search,ArrowUpRight,ArrowRight,MapPin,Layers,Sun,Sunset,Moon,Plus,Minus,Maximize,House,Play,Pause,ChevronDown,X,BookOpen,Building2,Utensils,GraduationCap,Trees,Volleyball,Info,Download,LocateFixed,Check,Compass,Map,RotateCcw,Share2,Camera,ChevronLeft,ChevronRight} from 'lucide-react';
import {CampusScene,tourIds} from './scene/CampusScene';
import {places,buildings,areas,categories,sources,findPlaces,mapFootprint,type Area,type Category,type Place} from './data/campus';
import {landPolygons,lakePolygons,lakeIsland,residentialWaters,roads} from './data/landscape';
const categoryIcons={study:GraduationCap,living:Building2,dining:Utensils,sports:Volleyball,service:BookOpen,landscape:Trees};
const initialPlace=()=>{const id=new URLSearchParams(location.search).get('place');return places.find(p=>p.id===id)?.id??null;};
declare global {interface Window {__atlas?:{scene:CampusScene|null;select:(id:string)=>void;overview:()=>void;area:(a:Area)=>void;setPlanned:(v:boolean)=>void;setFallback:(v:boolean)=>void;setMode:(v:LightMode)=>void;getState:()=>unknown;exportModel:(id?:string)=>Promise<{data:ArrayBuffer;meshes:number}>};}}
function MiniMap({selected,onSelect,ids,interactive=false}:{selected:string|null;onSelect:(id:string)=>void;ids:Set<string>;interactive?:boolean}){return <svg className={interactive?'fallback-map':'mini-map'} viewBox="130 40 1170 1280" role="img" aria-label="大学城校区二维示意图">
 {landPolygons.map((p,i)=><polygon key={i} points={p.map(q=>q.join(',')).join(' ')} fill="#c4d0b5" stroke="#fbfaf5" strokeWidth="6"/>)}
 {[...lakePolygons,...residentialWaters].map((p,i)=><polygon key={i} points={p.map(q=>q.join(',')).join(' ')} fill="#8bb9bc"/>)}
 <polygon points={lakeIsland.map(q=>q.join(',')).join(' ')} fill="#c4d0b5"/>{roads.filter(r=>r.main).map((r,i)=><polyline key={i} points={r.points.map(q=>q.join(',')).join(' ')} fill="none" stroke="#e6e6d8" strokeWidth="17"/>)}
 {buildings.filter(b=>b.width>0).map(b=>{const id=b.placeIds.find(id=>ids.has(id));if(!id)return null;const sel=b.placeIds.includes(selected??'');return <g key={b.id} role={interactive?'button':undefined} tabIndex={interactive?0:undefined} aria-label={places.find(p=>p.id===id)?.name} onClick={()=>onSelect(id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(id);}}} style={{cursor:'pointer'}}><polygon points={mapFootprint(b).map(p=>p.join(',')).join(' ')} fill={sel?'#a7473c':'#eee8d5'} stroke={sel?'#a7473c':'#9caa92'} strokeWidth={sel?5:2}/>{sel&&<circle cx={b.position[0]} cy={b.position[1]} r="18" fill="#aa4e42" stroke="white" strokeWidth="5"/>}</g>;})}
 {interactive&&places.filter(p=>p.landmark&&ids.has(p.id)).map(p=><text key={p.id} x={p.position[0]} y={p.position[1]+37} textAnchor="middle" fontSize="18" fill="#354a3e">{p.name}</text>)}
 </svg>;}
function App(){const host=useRef<HTMLDivElement>(null),labels=useRef<HTMLDivElement>(null),scene=useRef<CampusScene|null>(null),tourIndex=useRef(0);const [selected,setSelected]=useState<string|null>(initialPlace);const [detailCollapsed,setDetailCollapsed]=useState(true);const [query,setQuery]=useState(''),[area,setArea]=useState<Area|'all'>('all'),[category,setCategory]=useState<Category|'all'>('all'),[planned,setPlanned]=useState(()=>places.find(p=>p.id===initialPlace())?.status==='planned'),[labelOn,setLabelOn]=useState(true),[trafficOn,setTrafficOn]=useState(()=>new URLSearchParams(location.search).get('traffic')!=='off'),[mode,setMode]=useState<LightMode>(()=>parseLightMode(new URLSearchParams(location.search).get('light'))),[tour,setTour]=useState(false),[ready,setReady]=useState(false),[fallback,setFallback]=useState(new URLSearchParams(location.search).has('2d')),[about,setAbout]=useState(false),[filters,setFilters]=useState(false),[expanded,setExpanded]=useState(false),[exporting,setExporting]=useState(false),[toast,setToast]=useState(''),[orbit,setOrbit]=useState(false);
 const results=useMemo(()=>findPlaces(query,area,category,!!planned),[query,area,category,planned]);const ids=useMemo(()=>new Set(results.map(p=>p.id)),[results]);const place=places.find(p=>p.id===selected);const total=places.filter(p=>p.status==='built').length;
 const stopOrbit=()=>{setOrbit(false);scene.current?.setOrbit(false);};
 const clearView=()=>{const u=new URL(location.href);u.searchParams.delete('view');u.searchParams.delete('photo');history.replaceState({},'',u);};
 const choose=(id:string)=>{stopOrbit();clearView();const p=places.find(p=>p.id===id);if(!p)return;if(p.status==='planned')setPlanned(true);if(!ids.has(id)){setQuery('');setArea('all');setCategory('all');}if(id===selected)scene.current?.focus(id);setSelected(id);setExpanded(false);const u=new URL(location.href);u.searchParams.set('place',id);u.searchParams.delete('photo');history.replaceState({},'',u);};
 const reset=()=>{stopOrbit();clearView();setSelected(null);setTour(false);setArea('all');setCategory('all');setQuery('');scene.current?.overview();const u=new URL(location.href);u.searchParams.delete('place');u.searchParams.delete('photo');history.replaceState({},'',u);};
 const goArea=(a:Area|'all')=>{stopOrbit();clearView();setArea(a);setSelected(null);setTour(false);setQuery('');setExpanded(false);const u=new URL(location.href);u.searchParams.delete('place');u.searchParams.delete('photo');history.replaceState({},'',u);if(a==='all')scene.current?.overview();else scene.current?.area(a);};
 useEffect(()=>{if(fallback){setReady(true);return;}if(!host.current||!labels.current)return;let s:CampusScene;try{s=new CampusScene(host.current,labels.current,{select:id=>{setTour(false);choose(id);},ready:()=>setReady(true),error:msg=>{setToast(msg);if(msg.includes('二维'))setFallback(true);},manual:()=>{setTour(false);setOrbit(false);}});scene.current=s;const id=initialPlace();if(id)s.focus(id,true);else s.overview(true);}catch(e){setFallback(true);setReady(true);setToast('当前设备采用二维地图模式，地点搜索仍可使用。');return;}return ()=>{s.dispose();scene.current=null;};},[fallback]);
 useEffect(()=>{scene.current?.filter(ids,!!planned);},[ids,planned,ready,fallback]);
 useEffect(()=>{const shared=new URLSearchParams(location.search).get('view');if(shared&&scene.current?.restoreView(shared))return;if(!selected)return;const ref=new URLSearchParams(location.search).get('photo');const view=photoViews.find(v=>v.id===ref&&v.placeId===selected);if(view)scene.current?.photoView(view.id);else scene.current?.focus(selected);},[selected,ready,fallback]);
 useEffect(()=>{scene.current?.lighting(mode);const u=new URL(location.href);u.searchParams.set('light',mode);history.replaceState({},'',u);},[mode,ready,fallback]);
 useEffect(()=>{scene.current?.labelsVisible(labelOn);},[labelOn,ready,fallback]);
 useEffect(()=>{scene.current?.trafficVisible(trafficOn);const u=new URL(location.href);u.searchParams.set('traffic',trafficOn?'on':'off');history.replaceState({},'',u);},[trafficOn,ready,fallback]);
 useEffect(()=>{if(!about)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector('.about-modal') as HTMLElement;const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const nodes=Array.from(dialog.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus();};},[about]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return ()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{if(!tour)return;setQuery('');setArea('all');setCategory('all');choose(tourIds[tourIndex.current%tourIds.length]);const timer=setInterval(()=>{tourIndex.current=(tourIndex.current+1)%tourIds.length;choose(tourIds[tourIndex.current]);},6500);return ()=>clearInterval(timer);},[tour]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAbout(false);setFilters(false);setExpanded(false);setTour(false);setOrbit(false);scene.current?.setOrbit(false);}};window.addEventListener('keydown',handler);return ()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{window.__atlas={scene:scene.current,select:choose,overview:reset,area:goArea,setPlanned,setFallback,setMode,getState:()=>({selected,area,category,planned,mode,tour,ready,fallback,results:results.length}),exportModel:async(id)=>{if(!scene.current)throw new Error('请切换至三维模式后导出');return scene.current.exportModel(id);}};});
 async function exportModel(id='campus'){if(!scene.current){setToast('请切换到三维模式后导出模型');return;}setExporting(true);try{const {data}=await scene.current.exportModel(id);const url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download=id==='campus'?'gdut-campus.glb':`${id}.glb`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setToast('模型已导出，并通过重新加载检查');}catch(e){setToast('导出未完成：'+String(e));}finally{setExporting(false);}}
 function toggleTour(){stopOrbit();clearView();if(fallback){setToast('自动游览在三维模式中提供');return;}if(!tour)tourIndex.current=0;setTour(v=>!v);}
 function preset(v:'overview'|'north'|'south'|'east'|'west'|'top'|'front'|'back'){stopOrbit();setTour(false);clearView();scene.current?.landmarkView(v);}
 function toggleOrbit(){setTour(false);clearView();const ok=scene.current?.setOrbit(!orbit)??false;setOrbit(ok);if(!orbit&&!ok)setToast('当前采用减少动画或二维模式，可使用方向视角按钮');}
 async function shareView(){const u=new URL(location.href);u.searchParams.delete('photo');if(scene.current)u.searchParams.set('view',scene.current.captureView());u.searchParams.set('light',mode);try{await navigator.clipboard.writeText(u.href);setToast(['127.0.0.1','localhost','[::1]'].includes(u.hostname)?'视角链接已复制；当前为本机地址，公网部署后才能发给别人':'已复制当前视角链接，可以发给朋友');}catch{setToast('浏览器未允许复制，已把视角写入地址栏，可手动复制');}history.replaceState({},'',u);}
 function saveImage(){if(!scene.current){setToast('截图需要切换至三维模式');return;}const a=document.createElement('a');a.href=scene.current.snapshot();a.download='广工-'+(place?.name??'校园总览')+'.png';a.click();setToast('已保存当前三维画面（不含网页控件）');}
 function stepTour(direction:number){stopOrbit();setTour(false);const current=tourIds.indexOf(selected??'');tourIndex.current=(current+direction+tourIds.length)%tourIds.length;choose(tourIds[tourIndex.current]);}
 return <div className={'app '+mode}>
 <header className="topbar"><a className="brand" href="./" onClick={e=>{e.preventDefault();reset();}}><img className="gdut-brand" src="./brand/gdut-horizontal.png" alt="广东工业大学 · GUANGDONG UNIVERSITY OF TECHNOLOGY"/><span className="brand-project">校园漫游<span className="brand-en">大学城 · 3D</span></span></a><div className="campus-title"><span className="live-dot"/>大学城校区<span className="top-divider"/>广州 · 中国</div><div className="header-actions"><span className="local-badge">团结 · 勤奋 · 求是 · 创新</span><button className="about-btn" aria-label="关于地图" onClick={()=>setAbout(true)}><Info size={17}/><span>关于地图</span></button></div></header>
 <aside className={'sidebar '+(expanded?'expanded':'')}><button className="mobile-handle" onClick={()=>setExpanded(v=>!v)} aria-label={expanded?'收起地点列表':'展开地点列表'}><span/></button><div className="intro"><span className="eyebrow">GDUT / 大学城校区</span><h1>团结湖畔，<br/>又见广工。</h1><p>从正门柱廊，到工大魔方。</p></div>
 <div className="search-wrap"><Search size={18}/><input value={query} onFocus={()=>{if(innerWidth<760)setExpanded(true);}} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&results[0]){setTour(false);choose(results[0].id);}}} placeholder="搜索建筑、食堂或宿舍…" aria-label="搜索校园地点"/>{query?<button aria-label="清除搜索" onClick={()=>setQuery('')}><X size={15}/></button>:<kbd>↵</kbd>}</div>
 <div className="area-tabs" aria-label="校园区域">{(['all','academic','east','west'] as const).map(a=><button key={a} className={area===a?'active':''} onClick={()=>goArea(a)}>{a==='all'?'全校':areas[a].name}</button>)}</div>
 <div className="sidebar-scroll"><div className="category-grid"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}><Map size={15}/>全部地点</button>{(Object.keys(categories) as Category[]).map(c=>{const Icon=categoryIcons[c];return <button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}><Icon size={15}/>{categories[c].name}</button>;})}</div>
 {!query&&area==='all'&&category==='all'&&<button className="featured" onClick={()=>{setTour(false);choose('library');}}><span className="featured-tag">广工地标 / 01</span><div><BookOpen size={34} strokeWidth={1}/><span><strong>湖畔的「工大魔方」</strong><small>走近图书馆的另一面</small></span><ArrowUpRight size={20}/></div></button>}
 <div className="list-heading"><span>{query?'搜索结果':'探索校园'}</span><small>{results.length} 个地点</small></div>
 <div className="place-list">{results.length?results.map(p=>{const Icon=categoryIcons[p.category];return <button key={p.id} className={'place-row '+(p.id===selected?'selected':'')} onClick={()=>{setTour(false);choose(p.id);}}><span className="place-icon" style={{color:categories[p.category].color}}><Icon size={17}/></span><span className="place-text"><strong>{p.name}{p.status==='planned'&&<em>规划</em>}</strong><small>{areas[p.area].name} · {categories[p.category].name}</small></span><ArrowUpRight className="row-arrow" size={15}/></button>;}):<div className="empty"><Search size={28}/><strong>暂时没有找到这个地点</strong><p>试试“图书馆”“教一”或“东10”</p><button onClick={()=>{setQuery('');setCategory('all');setArea('all');}}>清除筛选</button></div>}</div></div>
 <footer className="sidebar-footer"><span><span className="live-dot"/>{total} 个校园地点</span><button onClick={()=>setAbout(true)}>资料与说明 <ArrowUpRight size={12}/></button></footer></aside>
 <main className="map-stage"><div className="scene-host" ref={host}/><div className="map-labels" ref={labels}/>{fallback&&<MiniMap selected={selected} ids={ids} onSelect={choose} interactive/>}
 <div className="map-top"><div className="view-caption"><span className="eyebrow">广东工业大学 · 大学城</span><strong>{place?.name??(area==='all'?'把广工，装进眼前。':areas[area].name)}</strong><small>{fallback?'二维示意':'3D 微缩沙盘'} / {place?'地标近景':area==='all'?'全校总览':areas[area].letter+' 区'}</small></div><div className="mode-switch" aria-label="光照模式"><button aria-label="日间光照" aria-pressed={mode==='day'} className={mode==='day'?'active':''} onClick={()=>setMode('day')}><Sun size={16}/><span>日间</span></button><button aria-label="黄昏光照" aria-pressed={mode==='sunset'} className={mode==='sunset'?'active':''} onClick={()=>setMode('sunset')}><Sunset size={16}/><span>黄昏</span></button><button aria-label="晚霞光照" aria-pressed={mode==='afterglow'} className={mode==='afterglow'?'active':''} onClick={()=>setMode('afterglow')}><Sunset size={16}/><span>晚霞</span></button><button aria-label="夜间光照" aria-pressed={mode==='night'} className={mode==='night'?'active':''} onClick={()=>setMode('night')}><Moon size={16}/><span>夜间</span></button></div></div>
 {!ready&&<div className="loading"><Layers size={32}/><strong>正在展开你的校园…</strong><span>连接每一段广工记忆</span></div>}
 <div className="map-tools"><button className="compass" title="北向复位" aria-label="北向复位" onClick={()=>{stopOrbit();clearView();setTour(false);scene.current?.north();}}><span>N</span><Compass size={25} className="compass-needle" strokeWidth={1.3}/></button><div className="tool-group"><button aria-label="放大" title="放大" onClick={()=>scene.current?.zoom(.8)}><Plus size={20}/></button><button aria-label="缩小" title="缩小" onClick={()=>scene.current?.zoom(1.25)}><Minus size={20}/></button></div><div className="tool-group"><button title="回到总览" aria-label="回到总览" onClick={reset}><House size={19}/></button><button title="俯视地图" aria-label="俯视地图" onClick={()=>{stopOrbit();clearView();setTour(false);scene.current?.top();}}><LocateFixed size={19}/></button><button title="地图图层" aria-label="地图图层" className={filters?'active':''} onClick={()=>setFilters(v=>!v)}><Layers size={19}/></button><button title="分享当前视角" aria-label="分享当前视角" onClick={shareView}><Share2 size={18}/></button><button title="保存地图截图" aria-label="保存地图截图" onClick={saveImage}><Camera size={18}/></button><button title="全屏" aria-label="全屏" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>setToast('当前窗口不支持全屏'));}}><Maximize size={18}/></button></div></div>
 {filters&&<div className="layer-panel"><strong>地图图层</strong><label><input type="checkbox" checked={labelOn} onChange={e=>setLabelOn(e.target.checked)}/>建筑名称</label><label><input type="checkbox" checked={trafficOn} disabled={fallback} onChange={e=>setTrafficOn(e.target.checked)}/>车流与骑行人流</label><label><input type="checkbox" checked={!!planned} onChange={e=>setPlanned(e.target.checked)}/>规划建筑 <small>独立显示</small></label><label><input type="checkbox" checked={fallback} onChange={e=>{stopOrbit();setFallback(e.target.checked);setTour(false);}}/>二维地图</label><p>规划状态依据所提供的官方地图。</p></div>}
 <div className="bottom-dock"><button className={'tour-btn '+(tour?'playing':'')} onClick={toggleTour}>{tour?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}<span>{tour?'暂停校园漫游':'开启校园漫游'}</span><span className="tour-count">08</span></button><button className="tour-step" aria-label="上一个地标" onClick={()=>stepTour(-1)}><ChevronLeft size={17}/></button><button className="tour-step" aria-label="下一个地标" onClick={()=>stepTour(1)}><ChevronRight size={17}/></button><span className="gesture-hint">拖动旋转 · 滚轮缩放 · 右键平移</span></div>
 <div className="mini-panel"><MiniMap selected={selected} ids={new Set(places.filter(p=>p.status==='built').map(p=>p.id))} onSelect={choose}/><span><span className="live-dot"/>校园方位</span></div>
 {place&&<section className={'detail-card '+(detailCollapsed?'collapsed':'')} aria-label="地点详情"><div className="detail-top"><span className="detail-kicker">{areas[place.area].letter} / {areas[place.area].name} <span>·</span> {categories[place.category].name}</span><button aria-label="关闭地点详情" onClick={reset}><X size={18}/></button></div><h2>{place.name}<span>{place.landmark?'校园地标':place.status==='planned'?'规划建筑':''}</span></h2>{place.aliases[0]&&<p className="detail-alias">{place.aliases[0]}</p>}<button className="detail-toggle" onClick={()=>setDetailCollapsed(v=>!v)} aria-expanded={!detailCollapsed}>{detailCollapsed?'展开详情':'收起详情'}<ChevronDown size={13}/></button><div className="landmark-controls" aria-label="建筑视角"><div className="landmark-presets">{([['overview','全景'],['north','北侧'],['south','南侧'],['east','东侧'],['west','西侧'],['top','俯视']] as const).map(([v,label])=><button disabled={fallback} key={v} onClick={()=>preset(v)}>{label}</button>)}{place.id==='culture'&&<><button disabled={fallback} onClick={()=>preset('front')}>入口正面</button><button disabled={fallback} onClick={()=>preset('back')}>体育场侧</button></>}</div><div className="landmark-actions"><button disabled={fallback} className={orbit?'active':''} aria-pressed={orbit} onClick={toggleOrbit}>{orbit?<Pause size={13}/>:<RotateCcw size={13}/>} {orbit?'暂停环视':'环绕建筑'}</button><button onClick={shareView}><Share2 size={13}/>分享视角</button></div></div><p className="detail-copy">{place.description}</p><div className="detail-bottom"><span><MapPin size={14}/>大学城校区</span><button onClick={()=>{stopOrbit();clearView();scene.current?.focus(place.id);}}><RotateCcw size={14}/>重新定位</button></div>{photoViews.some(v=>v.placeId===place.id)&&<details className="photo-views"><summary>按官网照片视角核对 <ChevronDown size={13}/></summary><p>依据周围建筑推断的近似机位，非精确摄影测量。点击视角后可旋转继续观察。</p>{photoViews.filter(v=>v.placeId===place.id).map(v=><button key={v.id} onClick={()=>{stopOrbit();setTour(false);clearView();scene.current?.photoView(v.id);const u=new URL(location.href);u.searchParams.set('photo',v.id);history.replaceState({},'',u);}}>{v.title}</button>)}</details>}<details><summary>查看资料来源与模型说明 <ChevronDown size={13}/></summary><p>位置与外观为示意还原，非测绘模型。高度为估计；未知背面作简化处理。</p>{place.sourceIds.map(id=>{const s=sources.find(s=>s.id===id)!;return <a key={id} href={s.url} target="_blank" rel="noreferrer">{s.title} <ArrowUpRight size={12}/></a>;})}</details></section>}
 <div className="map-disclaimer">校园示意 · 非测绘及实时导航地图</div>
 </main>
 {toast&&<div className="toast" role="status"><Info size={16}/>{toast}</div>}
 {about&&<div className="modal-backdrop" onClick={()=>setAbout(false)}><section className="about-modal" role="dialog" aria-modal="true" aria-labelledby="about-title" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="关闭关于地图" onClick={()=>setAbout(false)} autoFocus><X size={21}/></button><span className="eyebrow">MADE FOR OUR CAMPUS</span><h2 id="about-title">把熟悉的广工，<br/>放进一个小小世界。</h2><p>这是广东工业大学大学城校区的交互微缩沙盘，依据你提供的官方校园地图，结合官方照片重建。包含教学区、生活东区和生活西区。</p><div className="about-stats"><div><strong>03</strong><span>校园分区</span></div><div><strong>{total}</strong><span>已建地点</span></div><div><strong>08</strong><span>重点地标</span></div></div><h3>关于还原</h3><p>使用示意坐标与估计高度。图书馆等地标保留可辨认的形态，普通楼宇采用类型化表达。入口、营业时间及通行状态不作实时保证。规划建筑默认关闭。</p><h3>广工标识</h3><p>校徽与校名采用<a href="https://photo.gdut.edu.cn/info/1324/1992.htm" target="_blank" rel="noreferrer">广工图库官方横版标识</a>，保持原始颜色和比例。校训：团结、勤奋、求是、创新。本页为校园示意漫游项目。</p><h3>资料来源</h3><div className="source-list">{sources.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer"><span>{s.title}<small>{s.date} · {s.verification}</small></span><ArrowUpRight size={15}/></a>)}</div><p className="license-note">官网照片仅用于外观查阅参考，未作为网页贴图分发。网页的建筑几何与材质由代码生成。首次准备后，核心功能可离线使用。</p><div className="export-actions"><button disabled={exporting||fallback} onClick={()=>exportModel()}><Download size={16}/>{exporting?'正在导出并验证…':'导出校园建筑 GLB'}</button><button disabled={exporting||fallback} onClick={()=>exportModel('library')}><Download size={16}/>导出图书馆 GLB</button></div></section></div>}
 </div>;
}
export default App;

